### ISSUE TITLE
Auto add QCODE tags around selected text

### ISSUE THREAD

**Issue by elinw** [ropenscilabs/qcoder#18]
Implement auto pairing for (QCODE)(/QCODE).
https://ace.c9.io/#nav=higlighter

**Comment by elinw** [comment]
https://github.com/ajaxorg/ace/blob/v1.1.9/lib/ace/mode/behaviour/cstyle.js#L79  shows the JS pattern needed.

**Comment by laderast** [comment]
@elinw I'm going to see if I can help with this. I'm learning ShinyJS, and this seems to be a good reason to work on this.

**Comment by elinw** [comment]
Great!! Thanks.

**Comment by laderast** [comment]
I've put up a simple test app here that shows a way of doing text replacement to include qcodes: https://tladeras.shinyapps.io/add_code_test/ - I just wanted to get some feedback  before I implement it in the main qcode shiny app. 

You can select some text, and then select codes to add, and it will insert the appropriate QCODE tags.

Sorry for the delay - I ended up submitting a code fix for the `shinyAce` so that the selection code would work, and I'm still a little new to understanding javascript.

**Comment by elinw** [comment]
Cool! Taking a look at it now.

**Comment by elinw** [comment]
I really like the way that works, very clean and smooth.  @dsholler @bduckles @learithe Please check this out!

**Comment by laderast** [comment]
@elinw Thanks! I'll add this functionality to the main qcoder app.

I am trying to figure out how to place the cursor after someone selects and tags something. Supposedly, there is a `focus()` method for the Ace editor which does this, but I can't seem to get it to work.

**Comment by bduckles** [comment]
Very cool @laderast! Looks awesome and it really does improve the functionality. Thank you for adding to this project. I so appreciate it. 

I wonder if @kylehamilton might have some insights or resources to share on this Shiny problem.

**Comment by elinw** [comment]
I think focus should probably should go after the close of the tag.   I feel like that would be the most logical /natural place for someone coding to want to be.

**Comment by laderast** [comment]
Aha! Got it to work: https://tladeras.shinyapps.io/add_code_test/

I was using `useShinyjs()` in the wrong place. Focus now is on the end of the selection.

Ok, I'll work on adding it in this week. I'm just trying to figure out whether the `docs()` reactive is going to have issues when I add this.

**Comment by elinw** [comment]
Done!
