### ISSUE TITLE
App freeze when adding document

### ISSUE THREAD

**Issue by FrdVnW** [ropenscilabs/qcoder#62]
After loading a project, my app freeze when I try to add a new document. I saw a problem in the parameters of the call in the app, that are not as excepted by the function 'add_new_documents'. 

`292     qcoder::add_new_documents(files, doc_folder, docs_df_path)`

The two last parameters have to be inverted. 

`292     qcoder::add_new_documents(files, docs_df_path, doc_folder)`

I tried rapidly this, but it did not work. I used an alternative way, I will propose a new PR with it, more simple, but it works on my computer.

**Comment by elinw** [comment]
Okay this may be due to some recent changes.  One important thing is that all the functions must work on the command line and be able to use an arbitrary location for the files (not necessarily in the document folder in a project).  The current shiny app is for the simplest default uses and for beginners and small, well defined projects, but to be successful long run we will need to be more flexible.  I'm pretty sure this problem was introduced by some recent changes that fixed a different issue -- probably the path it is using is wrong.

**Comment by elinw** [comment]
Oh 
```
file_list <- files[["name"]]
```

Is a tibble, you need to change it to a vector.

**Comment by FrdVnW** [comment]
PR sent #65, if it helps ? I agree with the command line way, it is the base. I did not change the add_new_doc function which is OK.
I did not succeed to debug the ShinyFiles selection. I will try some other issues also ;-)

**Comment by elinw** [comment]
I think this is fixed ... at least it is not freezing for me. Please make a new issue if there is a still a problem since it will be due to a different problem.
